afl:
- libpng
- libtiff
- libxml2
- poppler
- openssl
aflfast:
- libpng
- libtiff
- libxml2
- poppler
- openssl
moptafl:
- libpng
- libtiff
- libxml2
- poppler
- openssl
fairfuzz:
- libpng
- libtiff
- libxml2
- poppler
- openssl
aflplusplus:
- libpng
- libtiff
- libxml2
- poppler
- openssl
honggfuzz:
- libpng
- libtiff
- libxml2
- poppler
- openssl
